version: 2
updates:
  # Defines update schedule
  - package-ecosystem: "npm"  # Specifies the package manager (npm)
    directory: "/"           # Specifies the directory where the package manager files are located
    schedule:
      interval: "weekly"     # Specifies the update frequency (weekly)
      time: "12:00"          # Specifies the time to check for updates (12:00 UTC)

# Additional settings to customize Dependabot behavior
# Check documentation for more options: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
options:
  # Ignore any dependencies with a lockfile
  ignore:
    - dependency-type: "all"
      directory: "/node_modules"

  # Allow version updates to be committed automatically
  auto-merge:
    # Automatically merge version updates
    enabled: true
    # Automatically merge patch updates
    patch: true
    # Automatically merge minor updates
    minor: true
    # Automatically merge major updates (use with caution)
    major: false
    # Automatically merge other types of updates
    # (pre-release, rebuilds, and lockfile updates)
    # use with caution
    dependency-ecosystem: npm
